# Generated by Django 3.2.9 on 2021-11-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0002_evento_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='id',
        ),
        migrations.AlterField(
            model_name='evento',
            name='title',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
