# Generated by Django 3.2.9 on 2021-11-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0006_alter_evento_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='id',
        ),
        migrations.AlterField(
            model_name='evento',
            name='start',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
