# Generated by Django 3.2.9 on 2021-11-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0008_rename_evento_eventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lugar', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.DeleteModel(
            name='Eventos',
        ),
    ]
